"""added embedding status and classification column

Revision ID: d640e0778dbe
Revises: e5d093ef6349
Create Date: 2026-01-31 14:10:42.202879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd640e0778dbe'
down_revision: Union[str, Sequence[str], None] = 'e5d093ef6349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding_status', sa.String(), default='pending'))
    op.add_column('documents', sa.Column('classification', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classification')
    op.drop_column('documents', 'embedding_status')
    
    # ### end Alembic commands ###
