"""add raw_text and cleaned_text to documents

Revision ID: e5d093ef6349
Revises: aa9ce7d6c57f
Create Date: 2026-01-31 12:53:40.941809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d093ef6349'
down_revision: Union[str, Sequence[str], None] = 'aa9ce7d6c57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('cleaned_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'cleaned_text')
    op.drop_column('documents', 'raw_text')
    # ### end Alembic commands ###
